#docker-compose.yml
version: "3.2"
services:
  app:
    build:
      context: .
      args:
        requirements: requirements/development.txt
    environment:
      - DJANGO_SETTINGS_MODULE=djangodocker.settings.development
    volumes:
      - ./:/app
    networks:
      - main
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: djangodocker_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - main  # Add the container to the network "main"
    ports:
      - "3306:3306"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/djangodocker/static
    ports:
      - "80:80"
    networks:
      - main  # Add the container to the network "main"
    depends_on:
      - app
networks:
  main:
